### ISSUE TITLE
Import statements in examples

### ISSUE THREAD

**Issue by og113** [Wall-Go/WallGoMatrix#31]
From Lauri's comment:
- At least some example .m files, eg examples/qcd.m, have hardcoded import path as <<../WallGoMatrix.m, and there is no useful error message to indicate where the example is supposed to be ran.
- And one final quality of life improvement would be to abort the example .m files if any package fails to import. Currently they just keep going and produce nonsense output. This and the point 3. above probably go beyond this PR though but I wanted to bring them up anyway.

**Comment by pschicho** [comment]
Both issues should be fixed in the indicated PR.
