### ISSUE TITLE
Paclet installation

### ISSUE THREAD

**Issue by og113** [Wall-Go/WallGoMatrix#35]
A Mathematica paclet installation would be preferable to what we currently do. @pschicho has started this, but I think we should adopt it in full.

See for instance:
- https://reference.wolfram.com/language/tutorial/Paclets.html
- https://community.wolfram.com/groups/-/m/t/1482624

**Comment by og113** [comment]
And for putting this on the Wolfram server:
- https://reference.wolfram.com/language/workflow/PrepareAPacletForPublication.html

**Comment by pschicho** [comment]
Could also be run with the workflows. I found this one (https://github.com/WolframResearch/WL-FunctionCompile-CI-Template) but it requires Wolfram ID stored as secrets on the GitHub organisation. And I am a bit insecure if sharing those with the organisation is within bounds of the license.

**Comment by pschicho** [comment]
Fixed together with `GroupMath` loading in PR#39.
